const { withInfoPlist, withXcodeProject, IOSConfig } = require('@expo/config-plugins');
const fs = require('fs');
const path = require('path');

const SCENE_DELEGATE_FILENAME = 'SceneDelegate.swift';

const SCENE_DELEGATE_CONTENT = `import UIKit

// Owns window creation now that the app has adopted the UIScene lifecycle -
// this iOS SDK requires it (a real device fails to launch without it, with
// "UIScene life cycle is required for apps built with this SDK"; the
// Simulator never enforced this, which is why it went unnoticed until the
// first real-device install). No AppDelegate override is needed: iOS reads
// the scene configuration straight from Info.plist's
// UIApplicationSceneManifest (added by this same plugin) when the app
// delegate doesn't implement application(_:configurationForConnecting:options:).
class SceneDelegate: UIResponder, UIWindowSceneDelegate {
  var window: UIWindow?

  func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
    guard let windowScene = scene as? UIWindowScene,
          let appDelegate = UIApplication.shared.delegate as? AppDelegate,
          let factory = appDelegate.reactNativeFactory
    else { return }

    let window = UIWindow(windowScene: windowScene)
    factory.startReactNative(withModuleName: "main", in: window, launchOptions: nil)
    self.window = window
    window.makeKeyAndVisible()
  }
}
`;

// This iOS SDK enforces the UIScene app lifecycle, but Expo's own template
// (SDK 57) doesn't scaffold one. Without this, a real-device launch crashes
// instantly and silently (EXC_BREAKPOINT) - the Simulator never catches it,
// so this only surfaces the first time someone actually installs on a phone.
// `ios/` is regenerated by `expo prebuild` and is gitignored, so the fix has
// to be a plugin, not a one-off hand-edit that the next prebuild deletes.
module.exports = function withUiSceneManifest(config) {
  config = withInfoPlist(config, (config) => {
    config.modResults.UIApplicationSceneManifest = {
      UIApplicationSupportsMultipleScenes: false,
      UISceneConfigurations: {
        UIWindowSceneSessionRoleApplication: [
          {
            UISceneConfigurationName: 'Default Configuration',
            UISceneDelegateClassName: '$(PRODUCT_MODULE_NAME).SceneDelegate',
          },
        ],
      },
    };
    return config;
  });

  config = withXcodeProject(config, (config) => {
    const projectRoot = config.modRequest.projectRoot;
    const sourceRoot = IOSConfig.Paths.getSourceRoot(projectRoot);
    const groupName = path.basename(sourceRoot);
    const relativeFilePath = path.join(groupName, SCENE_DELEGATE_FILENAME);

    fs.writeFileSync(path.join(sourceRoot, SCENE_DELEGATE_FILENAME), SCENE_DELEGATE_CONTENT);

    const project = config.modResults;
    if (!project.hasFile(relativeFilePath)) {
      const groupKey = project.findPBXGroupKey({ name: groupName });
      project.addSourceFile(relativeFilePath, {}, groupKey);
    }

    // app.json's ios.deploymentTarget only reaches some of these build
    // configurations (observed: 2 of 4 stayed at Expo's hardcoded 16.4
    // default after every prebuild - target-level settings win over
    // project-level, and only the project-level ones were getting patched).
    // Force every configuration explicitly so a stale 16.4 here can't
    // reintroduce "module has a minimum deployment target of iOS 17.0"
    // deep in a build log where it's easy to miss.
    const configurations = project.pbxXCBuildConfigurationSection();
    Object.keys(configurations).forEach((key) => {
      const entry = configurations[key];
      if (entry && typeof entry === 'object' && entry.buildSettings && entry.buildSettings.IPHONEOS_DEPLOYMENT_TARGET) {
        entry.buildSettings.IPHONEOS_DEPLOYMENT_TARGET = '17.0';
      }
    });

    return config;
  });

  return config;
};
